# Generated by Django 4.1.3 on 2022-11-25 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_hospedes', models.IntegerField(default=0)),
                ('banheiros', models.IntegerField(default=0)),
                ('pet', models.BooleanField(default=False)),
                ('limpeza', models.FloatField()),
                ('ativacao', models.DateTimeField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
