# Generated by Django 4.1.3 on 2022-11-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_ativacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Imovel',
        ),
    ]
