# Generated by Django 4.1.3 on 2022-11-25 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_movie_imovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=100)),
                ('taxa_plataforma', models.FloatField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('imovel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='api.imovel')),
            ],
        ),
    ]
