# Generated by Django 4.1.3 on 2022-11-25 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anuncio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='anuncio',
            unique_together={('imovel_id', 'id')},
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('check_in', models.CharField(max_length=100)),
                ('check_out', models.CharField(max_length=100)),
                ('preco_total', models.FloatField()),
                ('comentario', models.CharField(max_length=500)),
                ('hospedes', models.IntegerField(default=0)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('anuncio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.anuncio')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('anuncio_id', 'id')},
            },
        ),
    ]
