# Generated by Django 4.1.3 on 2022-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_anuncio_options_alter_anuncio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='ativacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='atualizacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='criacao',
            field=models.DateField(),
        ),
    ]
