# Generated by Django 4.1.3 on 2022-11-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_imovel_ativacao_alter_imovel_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='ativacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='atualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
